base_config: ./config/din_config/
base_expid: DIN_default
dataset_id: Ebnerd_small_x1

dataset_config:
    Ebnerd_small_x1:
        data_root: ./data/
        data_format: parquet
        train_data: ./data/Ebnerd_small_x1/train.parquet
        valid_data: ./data/Ebnerd_small_x1/valid.parquet
        test_data: ./data/Ebnerd_small_x1/test.parquet
        user_info: ./data/Ebnerd_small_x1/user_info.parquet
        item_info: ./data/Ebnerd_small_x1/item_info.parquet
        rebuild_dataset: False
        feature_cols:
            - {name: user_index, active: True, dtype: int, type: meta}
            - {name: item_index, active: True, dtype: int, type: meta}
            - {name: seq_len, active: True, dtype: int, type: meta}
            - {name: article_id, active: True, dtype: str, type: categorical, vocab_size: 3713, source: item}
            - {name: trigger_id, active: True, dtype: str, type: categorical, vocab_size: 2786}
            - {name: device_type, active: True, dtype: str, type: categorical, vocab_size: 5}
            - {name: is_sso_user, active: True, dtype: str, type: categorical, vocab_size: 4}
            - {name: gender, active: True, dtype: str, type: categorical, vocab_size: 4}
            - {name: postcode, active: True, dtype: str, type: categorical, vocab_size: 7}
            - {name: age, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: is_subscriber, active: True, dtype: str, type: categorical, vocab_size: 4}
            - {name: impression_hour, active: True, dtype: str, type: categorical, vocab_size: 26}
            - {name: impression_weekday, active: True, dtype: str, type: categorical, vocab_size: 9}
            - {name: publish_days, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: publish_hours, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: modify_days, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: modify_hours, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: premium, active: True, dtype: str, type: categorical, vocab_size: 4}
            - {name: article_type, active: True, dtype: str, type: categorical, vocab_size: 12, source: item}
            - {name: category, active: True, dtype: str, type: categorical, vocab_size: 24, source: item}
            - {name: sentiment_label, active: True, dtype: str, type: categorical, vocab_size: 5}
            - {name: ner_clusters, active: True, dtype: str, type: sequence, max_len: 5, vocab_size: 4310, source: item}
            - {name: topics, active: True, dtype: str, type: sequence, max_len: 5, vocab_size: 80, source: item}
            - {name: subcategory, active: True, dtype: str, type: sequence, max_len: 5, vocab_size: 128, source: item}
            - {name: total_inviews, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: total_pageviews, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: total_read_time, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: sentiment_score, active: True, dtype: str, type: categorical, vocab_size: 11}
            - {name: item_emb_d64, active: True, dtype: float, type: embedding, source: item, embedding_dim: 64}
        label_col: {name: click, dtype: float}


tuner_space:
    model_root: './checkpoints/'
    embedding_dim: 64
    dnn_hidden_units: [[1024, 512, 256]]
    attention_hidden_units: [[512, 256]]
    attention_hidden_activations: ReLU
    dnn_activations: ReLU
    attention_output_activation: null
    din_use_softmax: False
    embedding_regularizer: [1.e-6, 5.e-6, 1.e-5, 5.e-5, 1.e-4, 5.e-4, 1.e-3, 5.e-3]
    attention_dropout: 0.1
    net_dropout: 0.1
    batch_norm: [True, False]
    learning_rate: 1.e-3
    batch_size: 8192
    seed: 20242025
    group_id: user_index
    metrics: [[gAUC, AUC, logloss]]
    monitor: "gAUC"
    max_len: 64
