TWIN_KuaiVideo_x2_001_a1e6893e:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_002_4f20b72c:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_003_787f6610:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_004_719dcdcb:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_005_725208cf:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_006_1ef6acab:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_007_c279e976:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_008_ebc9ad6b:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_009_ad95648c:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_010_8194d195:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_011_17d2bac2:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_012_8f8e37bd:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_013_678dd01c:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_014_101f82aa:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_015_a1e6893e:
    Kc_cross_features: 0
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
TWIN_KuaiVideo_x2_016_4f20b72c:
    Kc_cross_features: 0
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: TWIN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
