ETA_KuaiVideo_x2_001_04869753:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_002_948f826b:
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_003_ca8e4078:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_004_67deddb7:
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_005_83af29fb:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_006_83acc0c3:
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_007_b35b9dc2:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    use_scale: true
    verbose: 1
ETA_KuaiVideo_x2_008_bcffede6:
    accumulation_steps: 4
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 2048
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    model: ETA
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 100
    use_features: null
    use_scale: true
    verbose: 1
