DCNv2_MicroVideo1.7M_x2_001_c1080b18:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_002_28af4a31:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_003_38f75c4c:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_004_3cfca8f6:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_005_eec78ed9:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_006_d6b8ebc9:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_007_c7c212fc:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_008_3692095f:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_009_4505be27:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
