TransAct_MicroVideo1.7M_x2_001_fab5aaa0:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 1
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_002_35e93237:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 1
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_003_f837e989:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 2
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_004_4a788c9a:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 2
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_005_f23347a1:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 3
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_006_2098c9b7:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 3
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 1
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_007_f837e989:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 1
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_008_4a788c9a:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 1
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_009_e6e88fed:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 2
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_010_34bde070:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 2
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_011_e417508c:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: true
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 3
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
TransAct_MicroVideo1.7M_x2_012_212c3688:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    concat_max_pool: false
    dataset_id: MicroVideo1.7M_x2
    dcn_cross_layers: 4
    dcn_hidden_units: [1024, 512, 256]
    debug_mode: false
    dim_feedforward: 512
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    first_k_cols: 3
    group_id: user_index
    hidden_activations: relu
    item_info_fields: 3
    learning_rate: 0.0005
    loss: binary_crossentropy
    max_len: 500
    metrics: [gAUC, AUC, logloss]
    mlp_hidden_units: []
    model: TransAct
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    sequence_item_field: click_sequence
    shuffle: true
    target_item_field: adgroup_id
    task: binary_classification
    time_window_ms: 86400000
    transformer_dropout: 0.1
    transformer_layers: 2
    use_features: null
    use_time_window_mask: false
    verbose: 1
