DCNv2_MicroVideo1.7M_x2_001_b39e439c:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_002_4c3d2483:
    batch_norm: false
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 1
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_003_e652f2f0:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_004_4cdc4f0f:
    batch_norm: false
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 2
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_005_28af4a31:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_006_50b74f1d:
    batch_norm: false
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_007_64672957:
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
DCNv2_MicroVideo1.7M_x2_008_141c9118:
    batch_norm: false
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    item_info_fields: 3
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DCNv2
    model_root: ./checkpoints/
    model_structure: parallel
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 4
    num_experts: 4
    num_workers: 4
    optimizer: adam
    parallel_dnn_hidden_units: [1024, 512, 256]
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    stacked_dnn_hidden_units: [500, 500, 500]
    task: binary_classification
    use_features: null
    use_low_rank_mixture: false
    verbose: 1
