SIM_Ebnerd_small_x1_001_68f63912:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_002_98942f3b:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_003_808640c0:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_004_95599a3b:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_005_14ce5294:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_006_96e9fb94:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_007_48c08a91:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_008_5f7579dc:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_009_5f7579dc:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_010_d25b57be:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_011_54c5a96c:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_012_88075946:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_013_88075946:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_014_3d88759a:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_015_5d4f6b83:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    verbose: 1
SIM_Ebnerd_small_x1_016_c06d5a63:
    accumulation_steps: 1
    alpha: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    beta: 1
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gsu_type: soft
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 100
    metrics: [gAUC, AUC, logloss]
    model: SIM
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    verbose: 1
