DIEN_KuaiVideo_x2_001_f571c88c:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_002_076d424c:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_003_48b3ab3d:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_004_c7b604bc:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_005_7c0bd2e2:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_006_a0765226:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_007_865bb28e:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_008_5309cb4a:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 1.0e-05
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_009_b3957c9e:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_010_5bffcc99:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AUGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_011_18374551:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: true
    use_features: null
    verbose: 1
DIEN_KuaiVideo_x2_012_7b5fd429:
    accumulation_steps: 1
    attention_activation: ReLU
    attention_dropout: 0.1
    attention_hidden_units: [256, 128]
    attention_type: din_attention
    aux_activation: ReLU
    aux_hidden_units: [100, 50]
    aux_loss_alpha: 0
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dien_neg_seq_field: []
    dien_sequence_field: click_sequence
    dien_target_field: adgroup_id
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    enable_sum_pooling: true
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    gru_type: AGRU
    item_info_fields: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: DIEN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_attention_softmax: false
    use_features: null
    verbose: 1
