MIRRN_MicroVideo1.7M_x2_001_178f899c:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_002_2c138cf4:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_003_bdc8eabb:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_004_b4d1e378:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_005_96df3078:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_006_a59f1ecd:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_007_38e42e00:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_008_1529a726:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_009_baa3ca9b:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 2
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_010_f1403140:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_011_186cf881:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_MicroVideo1.7M_x2_012_5584bee6:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: MicroVideo1.7M_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 4
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 5
    use_features: null
    use_scale: true
    verbose: 1
