MIRRN_KuaiVideo_x2_001_f531394f:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_002_2dc3bd94:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_003_f1bd188c:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_004_b7eb97ae:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_005_cc42deeb:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_006_a7d878cd:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_007_bbe65d3a:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 64
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_008_7ed440bb:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 64
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_KuaiVideo_x2_009_c5f98933:
    accumulation_steps: 1
    attention_dim: 512
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: KuaiVideo_x2
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.0001
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 64
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 50
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: gAUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 10
    use_features: null
    use_scale: true
    verbose: 1
