Base:
    model_root: './checkpoints/'
    num_workers: 4
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DIN_default: # This is a config template
    model: DIN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: [AUC, logloss]
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 8192
    embedding_dim: 64
    dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_use_softmax: False
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    max_len: 50
    accumulation_steps: 1
