MIRRN_Ebnerd_small_x1_001_8d589ad0:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 200
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_Ebnerd_small_x1_002_520e60fb:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 16
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 200
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_Ebnerd_small_x1_003_92812f29:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 200
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 50
    use_features: null
    use_scale: true
    verbose: 1
MIRRN_Ebnerd_small_x1_004_cb7e30c5:
    accumulation_steps: 1
    attention_dim: 128
    attention_dropout: 0.1
    batch_norm: true
    batch_size: 8192
    dataset_id: Ebnerd_small_x1
    debug_mode: false
    dnn_activations: relu
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 2
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_index
    hash_bits: 32
    learning_rate: 0.001
    loss: binary_crossentropy
    max_len: 200
    metrics: [gAUC, AUC, logloss]
    model: MIRRN
    model_root: ./checkpoints/
    monitor: {AUC: 1, gAUC: 1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_heads: 1
    num_workers: 4
    optimizer: adam
    pickle_feature_encoder: true
    reuse_hash: false
    save_best_only: true
    seed: 20242025
    short_seq_len: 50
    shuffle: true
    task: binary_classification
    topk: 20
    use_features: null
    use_scale: true
    verbose: 1
